services:
  postgres:
    image: postgres:15-alpine
    container_name: kan-todo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kan_todo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3.0
    container_name: kan-todo-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DISABLE_EVENTS=1
      - ACTIVATE_PRO=0
    volumes:
      - "./infra/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  postgres_data:
